### ISSUE TITLE
Project Resource: Add subscription association capabilities

### ISSUE THREAD

**Issue by gramsa49** [AxtonGrams/terraform-provider-wiz#29]
Looks ok to me, thank you. Sample in docs would be nice to have, and corresponding link in 'wiz_project':

``` hcl
data "wiz_cloud_accounts" "aws-123456789" {
  filters {
        search="123456789"
  }
}

resource "wiz_project" "aws-project {
  name        = "aws-project"
  description = "aws-project"

cloud_account_link {
    cloud_account = tolist(data.wiz_cloud_accounts.aws-123456789.cloud_accounts)[0].id
    shared      = false
 }

  risk_profile {
    business_impact = "MBI"
  }
}
```

_Originally posted by @DmitriSmirnovCTL in https://github.com/AxtonGrams/terraform-provider-wiz/issues/19#issuecomment-1276749444_

**Comment by gramsa49** [comment]
Add all new parameters to wiz_project resource:

- identifiers
- project_owners
- security_champions
- cloud_organization_links.resource_groups
- cloud_account_links
- cloud_account_links.cloud_account
- cloud_account_links.shared
- cloud_account_links.environment
- cloud_account_links.resource_tags
- cloud_account_links.resource_groups
- cloud_account_links.

**Comment by gramsa49** [comment]
thanks for rebasing the feature branch.  This one will take me a little more time to review and merge.  I will review tomorrow and share any findings in the incident.

**Comment by jschoombee** [comment]
Thanks for taking the time, appreciate 👍

**Comment by gramsa49** [comment]
I found one defect in the PR.  If `identifiers` is defined on a resource, then `identifiers` is removed from the resource block, the update operation for removal does not actually remove the configuration parameters.  This results in perpetual change detection.

This is most likely the result of the json marshalling in the request payload where the null value is omitted from the payload.  We'll have to deviate from the vendor's schema in the golang struct vendor.UpdateProjectPatch to include null fields.

I suspect the same will also be true of SecurityChampions and ProjectOwners (new fields).

Include a comment above the struct to this effect if we have to deviate from the vendor's schema.

While testing this PR, I found the same to be true of risk_profile and created a separate issue to track that defect (#54).

**Comment by gramsa49** [comment]
I posted a series of proposed changes in the PR, mostly arround mirroring the GraphQL schema everywhere possible.  I realize that sometimes deviations are required; in those cases, I ask that a comment be added in the struct comments noting the deviation.

I would like to auto-generate internal/vendor/wiz.go at some point in the future (#53), which will require an accouting of all deviations.

Please review/address those comments and send a commit with the necessary changes.

**Comment by jschoombee** [comment]
I think an override might be something consider indeed, in many ways it simplifies. If refactored elsewhere, would also take care of edge cases like the identity providers, and possibly other unknowns too.

Thanks for the comments, will address tomorrow and put it through a few tests before pushing updates. To flag a deviation, where needed, I'll keep a consistent tag as a comment so that later auto generation can honor.

Will look into this more tomorrow morning.

**Comment by jschoombee** [comment]
I addressed the struct naming irregularities in the PR locally and all looks good. When testing I did uncover another example where it is not possible to unset `description`. Considering schema below, if we respect the graphql schema and don't `omitempty` on the struct field, it will never get unset; if we override the schema, the consequence is that changes to unrelated fields would unset `description` given current implementation of checking for resource data changes.

I think given patch inconsistencies with the API and that Wiz seems to opt for Override even individual field changes in the portal, perhaps we should favour override instead of patch.

It will take a bit more time but I'll start testing this out and before pushing further overrides, be keen to hear your thoughts.

Thank you

```
input UpdateProjectInput {
  id: ID!
  patch: UpdateProjectPatch
  override: UpdateProjectPatch
}

input UpdateProjectPatch {
  name: String
  description: String
  identifiers: [String!]
  businessUnit: String
  archived: Boolean
  projectOwners: [String!]
  securityChampions: [String!]
  riskProfile: ProjectRiskProfileInput
  repositoryLinks: [ProjectRepositoryLinkInput!]
  cloudAccountLinks: [ProjectCloudAccountLinkInput!]
  cloudOrganizationLinks: [ProjectCloudOrganizationLinkInput!]
  kubernetesClusterLinks: [ProjectKubernetesClusterLinkInput!]
}

**Comment by gramsa49** [comment]
The web interface looks to use override.  I agree that we should move in that direction.  We will have to deviate from the GraphQL schema, which is fine, we just need to add a comment to the struct on why we have the deviation for future reference.  This should be coupled with the removal of the change detection on each field; just pass everything every time.

The project resource schema doesn't change, only the implementation behind the schema changes, so this shouldn't have and adverse effect on things currently in state, outside resolving the longstanding issue of nullifying fields that were removed from the IaC.

Appreciate your efforts!

**Comment by jschoombee** [comment]
Thanks to you also for the reviews, happy to have been able to assist so far :)

The changes to use override have been pushed. Hopefully schema deviations should be minimal now, barring `UpdateProjectPatch` where the reason is documented. I noted the issue with risk profile in #54, I did not yet look into resolving this just yet and thought to keep this PR contained and plan to investigate separately.

**Comment by jschoombee** [comment]
Compliments of the season! 

I noticed changes to API behaviour post the holiday-break, the `slug` became mandatory for `UpdateProjectInput`. I suspect it might again be to do with Wiz's Cognito migration efforts, similar to what was seen with SAML IDP updates.

Also picked up an issue when testing project deletion, current implementation would rename the project to the slug uuid as opposed to archiving.

Was hoping you could clarify initial reason for setting slug as `uuid` at create time instead of using the wiz-generated value or computing the slug from the name? From my testing, I haven't been able to recreate a project with the same name or slug combination if either exists but this may also be new behaviour from Wiz's side. The description change for the slug in the schema will just need to change depending on the way forward.

I've rebased and pushed changes to include the slug for delete and update contexts. 

Thanks

**Comment by gramsa49** [comment]
I set the slug to uuid because it has to be globally unique within the tenant.  The project name did not have that constraint.  To avoid conflicts, I used something for the slug assured to be unique, indepenant from the project name.

Projects cannot be deleted, per se, they are simply marked as archived.  In the event a project needs to be recreated by Terraform (ForceNew), using the project name as the basis for the slug would lead to an error condition.

I have one comment here:
https://github.com/AxtonGrams/terraform-provider-wiz/blob/main/internal/provider/resource_project.go#L641-L644
```
/*
  Wiz does not support deleting projects, so we fake it by setting archived=true
  We also change the naem to avoid conflicts since project names must be unique to the org
*/
```

**Comment by jschoombee** [comment]
Thanks for explanation. The project URL is generated based on the slug, if omitted, Wiz will generate based on project name but in our case we set it to a UUID, so currently that would be something like: _https://app.wiz.io/projects/d2f75e0e-7db7-5f65-bcfb-927a9906995c_

If the project is destroyed and possibly unarchived in future, it could become quite difficult to identify if a naming convention was followed.

What do you think setting the slug at create to a concatenation of a self-generated slug and uuid? Assuming we use a slug package like [this](https://github.com/gosimple/slug), we could:
replace  `vars.Slug = uuid.New().String()` --> `vars.Slug = fmt.Sprintf("%s-%s", slug.Make(d.Get("name").(string)), uuid.New().String())`

Assuming below hcl example:
```
resource "wiz_project" "test" {
  name = "My project friendly name-test"
}
```

This would render a slug of `my-project-friendly-name-test-03aa0017-acb6-4d71-a208-e2d8aeb67509` and a project URL of https://app.wiz.io/p/my-project-friendly-name-test-03aa0017-acb6-4d71-a208-e2d8aeb67509 at create time as opposed to a UID alone as the URI. Then if it does get archived, there's a human readable trail.

Perhaps not for the next release as it'll need testing, but maybe something to think about.

**Comment by gramsa49** [comment]
My main thought is around what conditions would warrant unarchiving a project.  When the project is deleted in Terraform, it is removed from state, and there currently is not a way to get that back into state.  A Terraform import could be used, but I haven't tested anything related to imports at this time.  The alternative is to manually unarchive a project.

If the intent is to know the name of the project after deletion, we could append the original project name (at time of deletion) to the project description.  Something like:

```
Project name at time of archival: xxx
```

The other question I ask myself is what value, if any, is brought by unarchiving a project, versus recreating the project by the same name.  The findings, associations, etc. should be equivalent, unless I'm missing something.
